<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 6.0 (Python 3.9.6 on darwin)" generated="20250414 17:57:37.366" rpa="false" schemaversion="3">
<suite id="s1" name="Api" source="/Users/angelashi/Documents/GitHub/robotcache/api.robot">
<test id="s1-t1" name="Verify GET Request" line="7">
<kw name="Create Session" library="RequestsLibrary">
<arg>weather_api</arg>
<arg>https://www.metaweather.com</arg>
<arg>verify=true</arg>
<doc>Create Session: create a HTTP session to a server</doc>
<msg timestamp="20250414 17:57:37.499" level="INFO">Creating Session using : alias=weather_api, url=https://www.metaweather.com, headers={},                     cookies={}, auth=None, timeout=None, proxies=None, verify=True,                     debug=0 </msg>
<status status="PASS" starttime="20250414 17:57:37.499" endtime="20250414 17:57:37.501"/>
</kw>
<kw name="GET On Session" library="RequestsLibrary">
<var>${response}</var>
<arg>weather_api</arg>
<arg>/api/location/search/</arg>
<arg>params=query=london</arg>
<doc>Sends a GET request on a previously created HTTP Session.</doc>
<msg timestamp="20250414 17:57:38.159" level="WARN">Retrying (RetryAdapter(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)'))': /api/location/search/?query=london</msg>
<msg timestamp="20250414 17:57:38.389" level="WARN">Retrying (RetryAdapter(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)'))': /api/location/search/?query=london</msg>
<msg timestamp="20250414 17:57:38.831" level="WARN">Retrying (RetryAdapter(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)'))': /api/location/search/?query=london</msg>
<msg timestamp="20250414 17:57:38.871" level="FAIL">SSLError: HTTPSConnectionPool(host='www.metaweather.com', port=443): Max retries exceeded with url: /api/location/search/?query=london (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)')))</msg>
<status status="FAIL" starttime="20250414 17:57:37.502" endtime="20250414 17:57:38.896"/>
</kw>
<kw name="Status Should Be" library="RequestsLibrary">
<arg>200</arg>
<arg>${response}</arg>
<doc>Fails if response status code is different than the expected.</doc>
<status status="NOT RUN" starttime="20250414 17:57:38.896" endtime="20250414 17:57:38.896"/>
</kw>
<kw name="Get Value From Json" library="JSONLibrary">
<var>${location_type}</var>
<arg>${response.json()}</arg>
<arg>$[0].location_type</arg>
<doc>Get Value From JSON using JSONPath</doc>
<status status="NOT RUN" starttime="20250414 17:57:38.897" endtime="20250414 17:57:38.897"/>
</kw>
<kw name="Should Contain" library="BuiltIn">
<arg>${location_type[0]}</arg>
<arg>City</arg>
<doc>Fails if ``container`` does not contain ``item`` one or more times.</doc>
<status status="NOT RUN" starttime="20250414 17:57:38.898" endtime="20250414 17:57:38.898"/>
</kw>
<status status="FAIL" starttime="20250414 17:57:37.499" endtime="20250414 17:57:38.898">SSLError: HTTPSConnectionPool(host='www.metaweather.com', port=443): Max retries exceeded with url: /api/location/search/?query=london (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)')))</status>
</test>
<status status="FAIL" starttime="20250414 17:57:37.370" endtime="20250414 17:57:38.900"/>
</suite>
<statistics>
<total>
<stat pass="0" fail="1" skip="0">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat pass="0" fail="1" skip="0" id="s1" name="Api">Api</stat>
</suite>
</statistics>
<errors>
<msg timestamp="20250414 17:57:38.159" level="WARN">Retrying (RetryAdapter(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)'))': /api/location/search/?query=london</msg>
<msg timestamp="20250414 17:57:38.389" level="WARN">Retrying (RetryAdapter(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)'))': /api/location/search/?query=london</msg>
<msg timestamp="20250414 17:57:38.831" level="WARN">Retrying (RetryAdapter(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)'))': /api/location/search/?query=london</msg>
</errors>
</robot>
